### ISSUE TITLE
Gitee 无法获取组织

### ISSUE THREAD

**Issue by gif-gif** [guoyk93/gitdump#4]
<img width="745" alt="image" src="https://github.com/guoyk93/gitdump/assets/7123500/84b6a87b-1edb-49b3-80a1-da2cceb33b5e">

**Comment by gif-gif** [comment]
上面一行执行后报错，返回找不到页面

**Comment by gif-gif** [comment]
<img width="1066" alt="image" src="https://github.com/guoyk93/gitdump/assets/7123500/9f52221b-4dd7-40a4-bcc9-9b34b859602f">

**Comment by yankeguo** [comment]
我处理下

**Comment by yankeguo** [comment]
我测试了一下 Gitee 功能是 OK 的，是不是你的令牌创建的时候，权限不全？

![截屏2023-06-26 14 14 40](https://github.com/guoyk93/gitdump/assets/52509957/2067a78d-7fbf-47af-aa23-832b0188eb59)

https://gitee.com/profile/personal_access_tokens/new
