### ISSUE TITLE
Gitee 无法获取中文名称的仓库

### ISSUE THREAD

**Issue by gif-gif** [guoyk93/gitdump#5]
抓去后的数据只有仓库名称为英文的，中文名称的仓库都没有
大佬尽快帮解决下，最近急用谢谢

**Comment by yankeguo** [comment]
是 Gitee 么

**Comment by yankeguo** [comment]
有没有报错信息？我调用 Gitee 接口的时候，使用的是 `full_name` 字段，理论上无论你的仓库叫什么名字，这个字段都是英文的

![截屏2023-06-26 14 18 02](https://github.com/guoyk93/gitdump/assets/52509957/8ec3373c-570d-4e54-a079-f1314c8d5b8e)

**Comment by gif-gif** [comment]
是gitee
但没有报错信息：
userRepos := grace.Must(client.GetUserRepos(ctx))
这个api返回的就只有英文仓库名称的列表，中文的没有，是不是gitee api 问题

**Comment by yankeguo** [comment]
@jiriyao 你可以尝试访问 https://gitee.com/api/v5/users/你的用户名/repos 检查 API 有没有列出你的仓库
